测试停止

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -23,6 +23,11 @@ jobs:
           distribution: zulu
           cache: maven
 
+      - name: End
+        run: |
+          echo "Failed to start my-service!"
+          exit 1
+
       - name: mvn spring-javaformat:validate
         run: mvn spring-javaformat:validate
 
